apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins
  labels:
    app: jenkins
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins
  template:
    metadata:
      labels:
        app: jenkins
    spec:
      containers:
      - name: jenkins
        image: jenkins/jenkins:2.319.1-lts  
        env:
        - name: JAVA_OPTS
          value: "-Djenkins.install.runSetupWizard=false"  
        - name: JENKINS_ADMIN_PASSWORD
          value: "admin"  
        ports:
        - containerPort: 8080
          name: web
        - containerPort: 50000
          name: agent
        volumeMounts:
        - name: jenkins-data
          mountPath: /var/jenkins_home
      volumes:
      - name: jenkins-data
        emptyDir: {}

---
apiVersion: v1
kind: Service
metadata:
  name: jenkins-service
spec:
  type: NodePort  
  selector:
    app: jenkins
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30000 